website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy 
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app=Flask(__name__)
    app.config['SECRET_KEY'] = 'tibebe'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    



    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .model import User, Profileform
    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


    return app
def create_database(app):
    if not path.exists('website/' + DB_NAME):
        with app.app_context():
            db.create_all()
            print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, session, abort
from .model import User, Profileform
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import qrcode, io, base64


auth=Blueprint('auth',__name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password1 = request.form.get('password1')
        session['email']=email

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, password1):
                flash('Logged in successfully', category='success')
                login_user(user, remember=True)
                if current_user.is_admin:
                     profiles = Profileform.query.all()
                     print (profiles)
                     return render_template("admin.html", profiles=profiles)
                return redirect(url_for('views.profileform'))
              
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category= 'error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method =='POST':
        email=request.form.get('email')
        session['email']=email
        fullname=request.form.get('fullname')
        password1=request.form.get('password1')
        password2=request.form.get('password2')
        user = User.query.filter_by(email=email).first()

        

 
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash ('Email must be greater than 3 characters.', category='error')
        elif len(fullname) < 2:
            flash ('Full name must be greater than 1 characters.', category='error')
        elif password1 != password2:
            flash ('Password do not match.', category='error')
        elif len(password1) < 5:
            flash ('Password is too short. It must be greater than 4 characters.', category='error')
        else:
            new_user = User(email=email, fullname=fullname, password=password1)
            if email== 'admin@gmail.com':
                new_user.is_admin = True
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account is created', category='success')
            return redirect(url_for('views.profileform'))
        

    return render_template("signup.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, session, redirect, url_for, request
from flask_login import login_user, login_required, logout_user, current_user
from .model import User, Profileform
from datetime import datetime
import qrcode,io,base64
from io import BytesIO

from . import db



views=Blueprint('views',__name__)
@views.route('/')
def index():
    return render_template("index.html")

@views.route('/delete_profile/<int:profile_id>/<int:user_id>', methods=['GET', 'POST'])
@login_required
def delete_profile(profile_id, user_id):
    profile = Profileform.query.get(profile_id)
    user = User.query.get(user_id)
    db.session.delete(user)
    db.session.delete(profile)
    db.session.commit()
    logout_user()
    return redirect(url_for('auth.signup'))
    

@views.route('/update_profile/<int:profile_id>', methods=['GET','POST'])
@login_required
def update_profile(profile_id):
    profile= Profileform.query.get(profile_id)

    if request.method == 'POST':
        profile.name= name = request.form.get('name')
        profile.age= age= request.form.get('age')
        profile.height= height = request.form.get('height')
        profile.weight= weight = request.form.get('weight')
        profile.startdate =startdate= datetime.strptime(request.form.get('startdate'), '%Y-%m-%d')
        profile.enddate = enddate= datetime.strptime(request.form.get('enddate'), '%Y-%m-%d')
        profile.amount =amount= request.form.get('amount')
        profile.account =account= request.form.get('bank')
        profile.receipt = bytes(request.form.get('receipt'), 'utf-8')

        
        qr = qrcode.QRCode(version=1, box_size=10, border=5)
        qr.add_data(f'Name: {name}\nAge: {age}\nHeight: {height}\nWeight: {weight}\nStart date: {startdate}\nEnd date: {enddate}\nAmount: {amount}\nAccount: {account}')
        qr.make(fit=True)
        qr_img = qr.make_image(fill_color="black", back_color="white")

            
        qr_bytes = io.BytesIO()
        qr_img.save(qr_bytes, format='PNG')
        qr_bytes.seek(0)
        qr_data = qr_bytes.read()

        profile.qrcode = qr_data

        db.session.commit()
        return redirect(url_for('views.profile'))
    return render_template("update_profile.html", profile=profile, user=current_user)


@views.route('/profile')
@login_required
def profile():
    user = User.query.filter_by(email=current_user.email).first()
    profile = Profileform.query.filter_by(email=user.email).first()
    
        
    
    # Decode the receipt field in the Profileform object
    qr_code_image = base64.b64encode(profile.qrcode).decode('utf-8')
    
    # Convert the decoded QR code image to a data URL format
    qr_code_data_url = "data:image/png;base64,{}".format(qr_code_image)
    
    # Pass the data URL to the template
    return render_template("profile.html", profile=profile, user=user, qr_code_data_url=qr_code_data_url, profile_id=profile.id, user_id=user.id)



@views.route('/profileform', methods=['GET', 'POST'])
@login_required
def profileform():
    email=session['email']
    form = Profileform.query.filter_by(email=email).first()
    if form:
        return redirect(url_for('views.profile'))
    else:
        if request.method =='POST':
            email=session['email']
            name=request.form.get('name')
            age=request.form.get('age')
            height=request.form.get('height')
            weight=request.form.get('weight')
            startdate_str=request.form.get('startdate')
            startdate= datetime.strptime(startdate_str, '%Y-%m-%d')
            enddate_str = request.form.get('enddate')
            enddate = datetime.strptime(enddate_str, '%Y-%m-%d')
            amount=request.form.get('amount')
            account=request.form.get('bank')
            receipt1=request.form.get('receipt')
            receipt = bytes(receipt1, 'utf-8')

            # Generate QR code from form data
            qr = qrcode.QRCode(version=1, box_size=10, border=5)
            qr.add_data(f'Name: {name}\nAge: {age}\nHeight: {height}\nWeight: {weight}\nStart date: {startdate}\nEnd date: {enddate}\nAmount: {amount}\nAccount: {account}')
            qr.make(fit=True)
            qr_img = qr.make_image(fill_color="black", back_color="white")

            # Save QR code to database
            qr_bytes = io.BytesIO()
            qr_img.save(qr_bytes, format='PNG')
            qr_bytes.seek(0)
            qr_data = qr_bytes.read()

            newform=Profileform(email= email, name=name, age=age, height=height, weight=weight,startdate=startdate, enddate=enddate, amount=amount, account=account, receipt=receipt, qrcode=qr_data)
            db.session.add(newform)
            db.session.commit()
            return redirect(url_for('views.profile'))
    return render_template("profileform.html", user=current_user)

website/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/profileinfo.css" />
    <link rel="stylesheet" href="/static/style.css" />
    <title>Admin</title>
</head>
<body id="bodyadmin">
    <div class="nav-container" id="nav-container1">
        <div class="logo" id="logo1">
          <h2>NAD<span>Fitness</span></h2>
        </div>
  
        <div class="topnav" id="myTopnav">
          <a href="/logout" class="login">Logout</a>
          <a href="/profile" id="signup">Admin</a>
          <a href="#" class="icon">
            <i class="fa fa-bars" style="color: white"></i>
          </a>
        </div>
    </div>
    <div class="tableadmin">
    <table class="table2">
        <tr class="tr">
            <th>Name</th>
            <th>Email</th>
            <th>Age</th>
            <th>Height</th>
            <th>Weight</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Amount</th>
            <th>Bank</th>
            <th>Receipt</th>
        </tr>
        {% for profile in profiles %}
        <tr>
            <td>{{ profile.name }}</td>
            <td>{{ profile.email }}</td>
            <td>{{ profile.age }}</td>
            <td>{{ profile.height }}</td>
            <td>{{ profile.weight }}</td>
            <td>{{ profile.startdate }}</td>
            <td>{{ profile.enddate }}</td>
            <td>{{ profile.amount }}</td>
            <td>{{ profile.account }}</td>
            <td>{{ profile.receipt }}</td>
        </tr>
        {% endfor %}
    </table>
    </div>
</body>
</html>

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gym Website</title>
    <link rel="stylesheet" href="./static/style.css" />
    <script src="static/script.js" defer></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>
  <body>
    <div class="nav-container">
      <div class="logo">
        <h2>NAD<span>Fitness</span></h2>
      </div>

      <div class="topnav" id="myTopnav">
        <a href="#home" class="active">Home</a>
        <a href="#contact">Contact</a>
        <a href="#service">Services</a>
        <a href="#price">Pricing</a>
        <a href="/login" class="login">Login</a>
        <a href="/signup" id="signup">SignUp</a>
        <a href="#" class="icon">
          <i class="fa fa-bars" style="color: white"></i>
        </a>
      </div>
    </div>

    <div class="hero-section" id="home">
      <div class="text-section">
        <h1>Get Fit Strong And Motivated</h1>
        <p>
          Our web application provides a convenient solution for fitness enthusiasts who want to have access to multiple gym locations. With our single account, you can easily switch between gym locations and never miss a workout.
        </p>
        <button href="/signup" class="getStartedBtn">Sign Up</button>
       
        
      </div>
      <!-- <div class="img">
        <img src="./static/workout.jpg" alt="" />
      </div> -->
    </div>

    <!-- contact -->

    <div class="contact-container" id="contact">
      <div class="content">
        <div class="left-side">
          <div class="address details">
            <i class="fas fa-map-marker-alt"></i>
            <div class="topic">Address</div>
            <div class="text-one">WARSAW</div>
            <div class="text-two">POLAND</div>
          </div>
          <div class="phone details">
            <i class="fas fa-phone-alt"></i>
            <div class="topic">Phone</div>
            <div class="text-one">+0098 9893 5647</div>
            <div class="text-two">+0096 3434 5678</div>
          </div>
          <div class="email details">
            <i class="fas fa-envelope"></i>
            <div class="topic">Email</div>
            <div class="text-one">tibebe@gmail.com</div>
          </div>
        </div>
        <div class="right-side">
          <div class="topic-text">Send us a message</div>
          <p>If you want to contact us you can send us a message here</p>
          <form action="#">
            <div class="input-box">
              <input type="text" placeholder="Enter your name" />
            </div>
            <div class="input-box">
              <input type="text" placeholder="Enter your email" />
            </div>
            <div class="input-box message-box">
              <input type="textarea" placeholder="Message" />
            </div>
            <div class="button">
              <input type="button" value="Send Now" />
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- service section -->
    <div class="service" id="service">
      <div class="service-head">
        <h2>Our Service</h2>
      </div>
      <div class="card-container">
        <div class="card">
          <h3>Experience</h3>
          <p>
            Remarkable customer service, a safe, clean, comfortable environment
            and the best training floor around await you at your local World
            Gym.
          </p>
        </div>
        <div class="card">
          <h3>Full Equipment</h3>
          <p>
            for your satisfaction we include all types of gym equipment like
            dumbbell, barbell, treadmills, rowing machines, and many others
          </p>
        </div>
        <div class="card">
          <h3>Personal training</h3>
          <p>
            We have enough hall to include yoga classes, spinning, body pump and
            many others.
          </p>
        </div>
      </div>
    </div>

    <!-- price section  -->

    <div class="price-container" id="price">
      <div class="service-head">
        <h2>We offer our services with affordable prices</h2>
      </div>
      <div class="row1">
        <div class="card">
          <div>
            <h1>Full package</h1>
            <p>Aerobics</p>
            <p>Gymnasium</p>
            <p>Taekwondu</p>
            <p>Yoga</p>
            <h2>3000 Birr</h2>
          </div>
        </div>
        <div class="card">
          <div>
            <h1>Basic</h1>
            <p>Aerobics</p>
            <p>Gymnasium</p>
            <h2>2000 Birr</h2>
          </div>
        </div>
      </div>
      <div class="row2">
        <div class="card">
          <div>
            <h1>Student</h1>
            <p>Aerobics</p>
            <p>Gymnasium</p>
            <h2>1500 Birr</h2>
          </div>
        </div>
        
      </div>
    </div>

    <footer class="footer">
      <p>2023 All rights reserved.☺</p>
    </footer>
  </body>
</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="static/login.css" />
  </head>
  <body>
    
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category =='error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert" style="margin-bottom:0px;" >
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show"  role="alert" style="margin-bottom:0px; ">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}


    <div class="login-container">
      <form method="POST" class="loginForm">
        <h1 class="login">Log-in</h1>

        <input type="email" id="email" name="email" placeholder="Enter your email" />
        <input type="password" id="password1" name="password1" placeholder="Enter password" />

        <input type="submit" />
        <p>Don't have account?</p>
        <p><a href="/signup">Signup here</a></p>
        <p class="backhome"><a href="/">Back to home</a></p>
      </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    
  </body>
</html>

website/templates/profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Profile</title>
    <link rel="stylesheet" href="static/profileinfo.css" />
    <link rel="stylesheet" href="static/style.css" />
    <script src="static/script.js" defer></script>
    
  </head>
  <body>
  
    <div class="nav-container" id="nav-container1">
      <div class="logo" id="logo1">
        <h2>NAD<span>Fitness</span></h2>
      </div>

      <div class="topnav" id="myTopnav">
        <a href="/logout" class="login">Logout</a>
        <a href="/profile" id="signup">Profile</a>
        <a href="#" class="icon">
          <i class="fa fa-bars" style="color: white"></i>
        </a>
      </div>
    </div>
    


    <div class="container" >
    
    <h1 class="h1">Profile Information</h1>

    <div class="ad-board">
      <h1 style="text-align:center;">Avaliable for Advertisment.
      </h1>
    </div>
    <div style="display: flex; align-items: center; padding-top:30px; width:800px;" >
    <img class ="qrcode" src="{{ qr_code_data_url }}">
    <table class="table">
      <tr>
        <td>Email:</td>
        <td>{{ profile.email }}</td>
      </tr>
      <tr>
        <td>Name:</td>
        <td>{{ profile.name }}</td>
      </tr>
      <tr>
        <td>Age:</td>
        <td>{{ profile.age }}</td>
      </tr>
      <tr>
        <td>Height:</td>
        <td>{{ profile.height }}</td>
      </tr>
      <tr>
        <td>Weight:</td>
        <td>{{ profile.weight }}</td>
      </tr>
      <tr>
        <td>Start date:</td>
        <td>{{ profile.enddate}}</td>
      </tr>
      <tr>
        <td>End date:</td>
        <td>{{ profile.enddate }}</td>
      </tr>
      <tr>
        <td>Receipt</td><br>
        <td>{{ profile.receipt }}</td>
      </tr>
    </table>
    </div>

    <div class="buttons">
    <a href="{{ url_for('views.update_profile', profile_id=profile.id) }}">
      <button class="update-button">Update</button>
    </a>
    <form action="{{ url_for('views.delete_profile', profile_id=profile.id, user_id=user.id) }}" method="post">
      <button class="delete-button" type="submit">Delete</button>
    </form>
    </div>

    
  
    <div class="packages">
      <h2 style="margin-left: 260px;">Available gyms with profile</h2>
      <div class="cards">
        <div class="card" style="background-image: url(static/ayat.jpg); " data-amount="3000">
          <div class="card-body">
            <h1 class="card-title">Ayat Gym</h1><br>
            <p>A boutique gym that offers a range of classes, including cycling and TRX, in a serene and personalized setting.</p>
            <br>Located at 444 Birch Ave, Addis Ababa, Ethiopia.
          </div>
        </div>

        <div class="card" data-amount="2000">
          <div class="card-body">
            <h1 class="card-title">Sheger Gym</h1><br>
            <p>Specializes in weight training and bodybuilding, 
              with top-of-the-line equipment and knowledgeable personal trainers.</p><br>Located at 456 Elm Ave, Addis Ababa, Ethiopia.
            
          </div>
        </div>

        <div class="card" data-amount="1500">
          <div class="card-body">
            <h1 class="card-title">Kirkos Gym</h1><br>
            <p>A high-end gym that offers a range of luxurious amenities, including a hot tub, a lounge, and a private training studio.</p>
            <br>Located at 666 Elm Rd, Addis Ababa, Ethiopia.
          </div>
        </div>

        <div class="card" data-amount="1500">
          <div class="card-body">
            <h1 class="card-title">Bole Gym</h1><br>
            <p>A luxury gym that offers exclusive amenities, such as a rooftop pool and a smoothie bar.</p>
            <br>Located at 111 Pine St, Addis Ababa, Ethiopia.
          </div>
        </div>

        <div class="card" data-amount="1500">
          <div class="card-body">
            <h1 class="card-title">Merkato Gym</h1><br>
            <p>Offers a wide variety of classes, including dance and martial arts, as well as a co-ed sauna and steam room.</p>
            <br>Located at 222 Cedar Rd, Addis Ababa, Ethiopia.
          </div>
        </div>

        <div class="card" data-amount="1500">
          <div class="card-body">
            <h1 class="card-title">Arada Gym</h1><br>
            <p>Provides a range of services, including a full-service spa, a juice bar, and a sun deck.</p>
            <br>Located at 333 Maple Ln, Addis Ababa, Ethiopia.
          </div>
        </div>

        <div class="card" data-amount="1500">
          <div class="card-body">
            
            <h1 class="card-title">Addis Ababa Fitness Center</h1><br>
            <p>Offers a wide range of fitness classes, including yoga, 
              Pilates, and cardio. .</p><br>Located at 123 Main St, Addis Ababa, Ethiopia.
            
          </div>
        </div>

        <div class="card" data-amount="1500">
          <div class="card-body">
            <h1 class="card-title">Akaki Gym</h1><br>
            <p>A spacious gym that offers state-of-the-art equipment, group fitness classes, and personal training.</p>
            <br> Located at 555 Oak St, Addis Ababa, Ethiopia.
          </div>
        </div>

        <div class="card" data-amount="1500">
          <div class="card-body">
            
            <h1 class="card-title">Yirgacheffe Gym</h1><br>
            <p>A family-friendly gym that offers a variety of fitness classes.</p><br>Located at 789 Oak Blvd, Addis Ababa, Ethiopia.
          </div>
        </div>

        <div class="card" data-amount="1500">
          <div class="card-body">
            <h1 class="card-title">Nefas Silk Gym</h1><br>
            <p>A premium gym that offers a variety of specialized classes, including Pilates and barre.</p>
            <br>Located at 777 Pine Ave, Addis Ababa, Ethiopia.
          </div>
        </div>
      </div>
    </div>


    </div>

  </body>
  
</html>

website/templates/profileform.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Profile</title>
    <link rel="stylesheet" href="static/profile.css" />
    <link rel="stylesheet" href="static/style.css" />
    <script src="static/script.js" defer></script>
    
  </head>
  <body>
    <div class="nav-container" id="nav-container1">
      <div class="logo" id="logo1">
        <h2>NAD<span>Fitness</span></h2>
      </div>

      <div class="topnav" id="myTopnav">
        <a href="/logout" class="login">Logout</a>
        <a href="/profile" id="signup">Profile</a>
        <a href="#" class="icon">
          <i class="fa fa-bars" style="color: white"></i>
        </a>
      </div>
    </div>


    <div class="container">
      <div class="service-head">
        <h2>Profile</h2>
      </div>



      <form method="POST">
        <div class="row">
          <div class="col-25">
            <label for="email">Email</label>
          </div>
          <div class="col-75">
            <input
              type="text"
              id="email"
              name="email"
              placeholder="Your email.."
            />
          </div>
        </div>


        <div class="row">
          <div class="col-25">
            <label for="name">Name</label>
          </div>
          <div class="col-75">
            <input
              type="text"
              id="name"
              name="name"
              placeholder="Your name.."
            />
          </div>
        </div>



        <div class="row">
          <div class="col-25">
            <label for="age">Age</label>
          </div>
          <div class="col-75">
            <input type="text" id="age" name="age" placeholder="Your age.." />
          </div>
        </div>


        <div class="row">
          <div class="col-25">
            <label for="Height">Height</label>
          </div>
          <div class="col-75">
            <input
              type="text"
              id="height"
              name="height"
              placeholder="Your height.."
            />
          </div>
        </div>
        <div class="row">
          <div class="col-25">
            <label for="weight">Weight</label>
          </div>
          <div class="col-75">
            <input
              type="text"
              id="weight"
              name="weight"
              placeholder="Your weight.."
            />
          </div>
        </div>
     
        <div class="packages">
            <div class="cards">
              <div class="card" data-amount="3000">
                <div class="card-body">
                  <h1 class="card-title">Full Packages</h1>
                  <p>Aerobics</p>
                  <p>Gymnasium</p>
                  <p>Taekwondu</p>
                  <p>Yoga</p>
                  <h2>3000 Birr</h2>
                </div>
              </div>
  
              <div class="card" data-amount="2000">
                <div class="card-body">
                  <h1 class="card-title">Basic</h1>
                  <p>Aerobics</p>
                  <p>Gymnasium</p>
                  <h2>2000 Birr</h2>
                </div>
              </div>
  
              <div class="card" data-amount="1500">
                <div class="card-body">
                  <h1 class="card-title">Student</h1>
                  <p>Aerobics</p>
                  <p>Gymnasium</p>
                  <h2>1500 Birr</h2>
                </div>
              </div>
            </div>
          </div>
  
          <div class="row">
            <div class="col-25">
              <label for="name">Start date</label>
            </div>
            <div class="col-75">
              <input type="date" id="startdate" name="startdate" />
            </div>
          </div>
          <div class="row">
            <div class="col-25">
              <label for="name">End date</label>
            </div>
            <div class="col-75">
              <input type="date" id="enddate" name="enddate" />
            </div>
          </div>

          <div class="row">
            <div class="col-25">
              <label for="amount">Amount</label>
            </div>
            <div class="col-75">
              <input
                type="text"
                id="amount"
                name="amount"
                placeholder="Amount"
              />
            </div>
          </div>
  
          <div class="row">
            <div class="col-25">
              <label for="country">Bank Name</label>
            </div>
            <div class="col-75">
              <select id="bank" name="bank">
                <option value="CBE">CBE ACC No:#### #### #### ####</option>
                <option value="DASHEN">DASHEN ACC No:#### #### #### ####</option>
                <option value="ABYSSINIA">ABYSSINIA ACC No:#### #### #### ####</option>
                <option value="AWASH">AWASH ACC No:#### #### #### ####</option>
              </select>
            </div>
          </div>
  
          <div class="row">
            <div class="col-25">
              <label for="weight">Upload receipt image</label>
            </div>
            <div class="col-75">
              <input type="file" id="receipt" name="receipt" />
            </div>
          </div>

        <div class="row">
          <input type="submit"/>
        </div>
      </form>




      <div class="space"></div>
    </div>

    
    
  

    

  </body>
  
</html>